## Amount of Cargo machines per chunk (25 by default)
amount: 25

## Auto updater (true by default)
auto-update: true

## Size of the thread pool (4 by default)
## Only touch this setting when you know what you are doing!
thread-pool-size: 4

## If a claiming plugin is enabled, this setting prevents players from placing cargo outside of claimed areas
## This makes it impossible to "extend" existing networks from just outside the border in order to steal from claims
block-wilderness-cargo: false

## Permissions (false by default)
## Permission node: headlimiter.permission.<name>
## Example: headlimiter.permission.noob
##
## When permissions have been set to true, you can use the values here to set the amount of heads checked.
## You can add as many entries as you want.
## Order has to be reversed or breaky breaky
permissions: false
permission:
  ## sefi: 25
  ## walshy: 20
  ## alessio: 15
  ## jeff: 10
  noob: 5

## Item groups
## You can make your own item group see the example. Make sure that the example doesnt match up with any item ID's
## highly recommend prefixing or suffixing them. For example CARGO_GROUP or GROUP_CARGO.
##
##  cargo_group:
##    items-amount: 25
##    items:
##      - CARGO_NODE_INPUT
##      - CARGO_NODE_OUTPUT
##      - CARGO_NODE_OUTPUT_ADVANCED
##      - CARGO_NODE
##      - CARGO_MANAGER
##
block-limits:
  cargo_group:
    items-amount: 25
    items:
      - CARGO_NODE_INPUT
      - CARGO_NODE_OUTPUT
      - CARGO_NODE_OUTPUT_ADVANCED
      - CARGO_NODE
      - CARGO_MANAGER
    permission-amount:
      example_1: 50
      example_2: 100
      example_3: 150