## Amount of Cargo machines per chunk (25 by default)
amount: 25

## Auto updater (true by default)
auto-update: true

## Size of the thread pool (4 by default)
## Only touch this setting when you know what you are doing!
thread-pool-size: 4

## If a claiming plugin is enabled, this setting prevents players from placing cargo outside of claimed areas
## This makes it impossible to "extend" existing networks from just outside the border in order to steal from claims
block-wilderness-cargo: false

## Permissions (false by default)
## Permission node: headlimiter.permission.<name>
## Example: headlimiter.permission.noob
##
## When permissions have been set to true, you can use the values here to set the amount of heads checked.
## You can add as many entries as you want.
## Order has to be reversed or breaky breaky
permissions: false
permission:
  ## sefi: 25
  ## walshy: 20
  ## alessio: 15
  ## jeff: 10
  noob: 5
## Put the SlimefunItem ID (found in Items.yml) followed by the maximum number of those blocks you want to allow in
## a chunk. Please note this will not remove blocks retroactively only limit further placement.
## Example:
## CARGO_INPUT_NODE: 25
## NTW_BRIDGE: 100
## JEFFS_WEIRD_BOX: 0
block-limits:
  CARGO_NODE_INPUT: 25
  CARGO_NODE_OUTPUT: 25
  CARGO_NODE_OUTPUT_ADVANCED: 25
  CARGO_NODE: 25
  CARGO_MANAGER: 25